# Netlify configuration file

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "node build-client.js"

# Handle SPA routing (redirect all paths to index.html for client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
